import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2.112.3'

type Claim={job_id:string;tenant_id:string;appointment_id:string;patient_id:string;kind:string;phone:string;patient_name:string;scheduled_at:string;timezone:string;appointment_type:string;template_name:string;template_language:string;parameter_keys:string[];phone_number_id:string;graph_version:string;access_token_env:string;verify_token_env:string;app_secret_env:string;fallback_to_inbox:boolean}
type MetaConfig={tenant_id:string;whatsapp_phone_number_id:string;whatsapp_app_secret_env:string;whatsapp_access_token_env:string;whatsapp_graph_version:string}

function secretKey(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');if(modern){try{const p=JSON.parse(modern) as Record<string,string>;if(p.default)return p.default;const f=Object.values(p)[0];if(f)return f}catch{}}return Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY')||''}
const supabase=createClient(Deno.env.get('SUPABASE_URL')||'',secretKey(),{auth:{persistSession:false,autoRefreshToken:false}})
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8'}})}
function timingSafeEqual(a:string,b:string){const aa=new TextEncoder().encode(a),bb=new TextEncoder().encode(b);if(aa.length!==bb.length)return false;let d=0;for(let i=0;i<aa.length;i++)d|=aa[i]^bb[i];return d===0}
function normalizePhone(phone:string){const d=String(phone||'').replace(/\D/g,'');if(!d)return '';if((d.length===10||d.length===11)&&!d.startsWith('55'))return `55${d}`;return d}
function dateParts(iso:string,tz:string){const d=new Date(iso);return{date:new Intl.DateTimeFormat('pt-BR',{timeZone:tz||'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'numeric'}).format(d),time:new Intl.DateTimeFormat('pt-BR',{timeZone:tz||'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',hour12:false}).format(d)}}
function parameterValue(key:string,j:Claim){const p=dateParts(j.scheduled_at,j.timezone);return({patient_name:j.patient_name||'Paciente',appointment_date:p.date,appointment_time:p.time,appointment_type:j.appointment_type||'Consulta',appointment_id:j.appointment_id} as Record<string,string>)[key]??''}
function retryableStatus(s:number){return s===408||s===409||s===425||s===429||s>=500}
async function completeJob(jobId:string,success:boolean,o:{messageId?:string;error?:string;retryable?:boolean;metadata?:Record<string,unknown>}){const{data,error}=await supabase.rpc('service_complete_appointment_whatsapp_job',{p_job_id:jobId,p_success:success,p_provider_message_id:o.messageId??null,p_error:o.error??null,p_retryable:o.retryable??true,p_response_metadata:o.metadata??{}});if(error)throw new Error(`complete_job: ${error.message}`);return data}
async function metaPost(config:{phoneId:string;graphVersion:string;tokenEnv:string},payload:Record<string,unknown>){const token=Deno.env.get(config.tokenEnv);if(!token)throw new Error(`Secret ${config.tokenEnv} não configurado`);const r=await fetch(`https://graph.facebook.com/${config.graphVersion}/${config.phoneId}/messages`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',...payload})});let b:any=null;try{b=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(String(b?.error?.message||`Meta HTTP ${r.status}`)),{httpStatus:r.status,meta:b?.error});return b}

async function sendMetaTemplate(job:Claim){
  const phone=normalizePhone(job.phone);if(!phone)return completeJob(job.job_id,false,{error:'Telefone WhatsApp inválido ou ausente',retryable:false,metadata:{code:'invalid_phone'}})
  const token=Deno.env.get(job.access_token_env);if(!token)return completeJob(job.job_id,false,{error:`Secret ${job.access_token_env} não configurado na Edge Function`,retryable:false,metadata:{code:'provider_secret_missing'}})
  const keys=Array.isArray(job.parameter_keys)?job.parameter_keys:[]
  const components:any[]=[];const params=keys.map(k=>({type:'text',text:parameterValue(String(k),job)}));if(params.length)components.push({type:'body',parameters:params})
  const{data:tpl}=await supabase.from('appointment_communication_templates').select('provider_quick_reply_actions').eq('tenant_id',job.tenant_id).eq('kind',job.kind).eq('channel','whatsapp').eq('active',true).maybeSingle()
  const actions=(Array.isArray(tpl?.provider_quick_reply_actions)?tpl.provider_quick_reply_actions:[]).filter((x:any)=>['confirm','cancel','reschedule'].includes(String(x))).slice(0,3)
  actions.forEach((a:any,index:number)=>components.push({type:'button',sub_type:'quick_reply',index:String(index),parameters:[{type:'payload',payload:`APPT_${String(a).toUpperCase()}:${job.appointment_id}`}]}))
  const template:any={name:job.template_name,language:{code:job.template_language||'pt_BR'}};if(components.length)template.components=components
  let b:any;try{b=await metaPost({phoneId:job.phone_number_id,graphVersion:job.graph_version,tokenEnv:job.access_token_env},{recipient_type:'individual',to:phone,type:'template',template})}catch(e:any){return completeJob(job.job_id,false,{error:String(e.message).slice(0,450),retryable:retryableStatus(Number(e.httpStatus||0)),metadata:{http_status:e.httpStatus??null,meta_code:e.meta?.code??null,meta_subcode:e.meta?.error_subcode??null,fbtrace_id:e.meta?.fbtrace_id??null}})}
  const mid=b?.messages?.[0]?.id;if(!mid)return completeJob(job.job_id,false,{error:'Meta aceitou a requisição sem retornar message id',retryable:true})
  return completeJob(job.job_id,true,{messageId:mid,retryable:false,metadata:{wa_id:b?.contacts?.[0]?.wa_id??null,graph_version:job.graph_version,template_name:job.template_name,quick_reply_actions:actions}})
}

async function dispatch(req:Request,body:any){const token=req.headers.get('x-dispatch-token')||'';const{data:ok,error:ve}=await supabase.rpc('service_verify_appointment_dispatch_token',{p_token:token});if(ve||ok!==true)return json({error:'unauthorized'},401);const limit=Math.max(1,Math.min(100,Number(body?.limit||25)));const{data,error}=await supabase.rpc('service_claim_appointment_whatsapp_jobs',{p_limit:limit});if(error)return json({error:error.message},500);const jobs=(data||[]) as Claim[],results:any[]=[];for(const j of jobs){try{results.push({job_id:j.job_id,result:await sendMetaTemplate(j)})}catch(e){try{await completeJob(j.job_id,false,{error:(e as Error).message,retryable:true})}catch{}results.push({job_id:j.job_id,error:(e as Error).message})}}return json({claimed:jobs.length,results})}

async function verifyWebhook(url:URL){const mode=url.searchParams.get('hub.mode'),candidate=url.searchParams.get('hub.verify_token')||'',challenge=url.searchParams.get('hub.challenge')||'';if(mode!=='subscribe'||!candidate||!challenge)return new Response('Bad Request',{status:400});const{data,error}=await supabase.from('appointment_communication_channel_settings').select('whatsapp_verify_token_env').eq('whatsapp_provider','meta_cloud');if(error)return new Response('Internal Server Error',{status:500});const accepted=(data||[]).some(r=>{const exp=Deno.env.get(r.whatsapp_verify_token_env)||'';return exp&&timingSafeEqual(exp,candidate)});return accepted?new Response(challenge,{status:200}):new Response('Forbidden',{status:403})}
async function hmacSha256Hex(secret:string,data:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(data));return Array.from(new Uint8Array(sig)).map(b=>b.toString(16).padStart(2,'0')).join('')}

async function sendSessionText(config:MetaConfig,to:string,text:string){if(!text)return;await metaPost({phoneId:config.whatsapp_phone_number_id,graphVersion:config.whatsapp_graph_version,tokenEnv:config.whatsapp_access_token_env},{recipient_type:'individual',to:normalizePhone(to),type:'text',text:{preview_url:false,body:text.slice(0,4096)}})}
async function sendRescheduleList(config:MetaConfig,to:string,rows:any[]){const listRows=rows.slice(0,10).map(r=>({id:`APPT_SLOT:${r.option_token}`,title:String(r.option_label||'Novo horário').slice(0,24),description:String(r.option_description||'').slice(0,72)}));if(!listRows.length){await sendSessionText(config,to,'Não encontrei horários disponíveis nos próximos dias. A clínica pode ajudar pelo atendimento.');return}await metaPost({phoneId:config.whatsapp_phone_number_id,graphVersion:config.whatsapp_graph_version,tokenEnv:config.whatsapp_access_token_env},{recipient_type:'individual',to:normalizePhone(to),type:'interactive',interactive:{type:'list',body:{text:'Escolha um novo horário para sua consulta. O horário atual só será alterado depois da sua escolha.'},action:{button:'Ver horários',sections:[{title:'Horários disponíveis',rows:listRows}]}}})}
function inboundParts(message:any){let text='',action='';if(message?.type==='text')text=String(message?.text?.body||'');else if(message?.type==='button'){text=String(message?.button?.text||'');action=String(message?.button?.payload||'')}else if(message?.type==='interactive'){const br=message?.interactive?.button_reply,lr=message?.interactive?.list_reply;if(br){text=String(br.title||'');action=String(br.id||'')}else if(lr){text=String(lr.title||'');action=String(lr.id||'')}}return{text,action}}

async function processInbound(config:MetaConfig,message:any){const{id,type,from,context}=message||{};if(!id||!from)return false;const{text,action}=inboundParts(message);const receivedAt=message?.timestamp?new Date(Number(message.timestamp)*1000).toISOString():new Date().toISOString();const{data:result,error}=await supabase.rpc('service_process_appointment_whatsapp_inbound',{p_tenant_id:config.tenant_id,p_phone_number_id:config.whatsapp_phone_number_id,p_provider_message_id:String(id),p_from_phone:String(from),p_message_type:String(type||'unknown'),p_message_text:text||null,p_action_id:action||null,p_context_provider_message_id:context?.id?String(context.id):null,p_received_at:receivedAt});if(error){console.error('inbound-rpc',error.message);return false}if(result?.duplicate)return true
  try{
    if(result?.action==='show_reschedule_options'&&result?.patient_id&&result?.appointment_id){const{data:options,error:oe}=await supabase.rpc('service_prepare_whatsapp_reschedule_options',{p_tenant_id:config.tenant_id,p_patient_id:result.patient_id,p_appointment_id:result.appointment_id,p_limit:8});if(oe)await sendSessionText(config,from,'Não consegui abrir os horários agora. A clínica pode te ajudar pelo atendimento.');else await sendRescheduleList(config,from,options||[])}
    else if(result?.action==='rescheduled'&&result?.scheduled_at){const p=dateParts(result.scheduled_at,result.timezone||'America/Sao_Paulo');await sendSessionText(config,from,`Pronto. Sua consulta foi reagendada para ${p.date} às ${p.time}. Como o horário mudou, ela voltou para “aguardando confirmação”.`)}
    else if(result?.reply)await sendSessionText(config,from,String(result.reply))
  }catch(e){console.error('inbound-reply',(e as Error).message)}
  return true
}

async function processStatuses(config:MetaConfig,value:any){let processed=0;for(const st of value?.statuses||[]){const mid=String(st?.id||''),state=String(st?.status||'');if(!mid||!['sent','delivered','read','failed','deleted'].includes(state))continue;const eventAt=st?.timestamp?new Date(Number(st.timestamp)*1000).toISOString():new Date().toISOString(),firstError=st?.errors?.[0];const{data:job}=await supabase.from('appointment_communication_jobs').select('id,tenant_id,status,metadata,delivered_at').eq('provider','meta_cloud').eq('provider_message_id',mid).maybeSingle();if(!job||job.tenant_id!==config.tenant_id)continue;await supabase.from('appointment_communication_delivery_events').insert({tenant_id:job.tenant_id,job_id:job.id,provider:'meta_cloud',provider_message_id:mid,status:state,event_at:eventAt,error_code:firstError?.code?String(firstError.code):null,error_message:firstError?.title||firstError?.message||null,metadata:{recipient_id:st?.recipient_id??null,conversation_id:st?.conversation?.id??null}});if(state==='delivered')await supabase.from('appointment_communication_jobs').update({delivered_at:eventAt,updated_at:new Date().toISOString(),last_error:null}).eq('id',job.id);else if(state==='read')await supabase.from('appointment_communication_jobs').update({delivered_at:job.delivered_at||eventAt,metadata:{...(job.metadata||{}),whatsapp_read_at:eventAt},updated_at:new Date().toISOString(),last_error:null}).eq('id',job.id);else if(state==='failed')await supabase.from('appointment_communication_jobs').update({status:'ready',channel:'inbox',provider:null,provider_message_id:null,attempt_count:0,next_attempt_at:null,locked_at:null,failed_at:eventAt,last_error:String(firstError?.title||firstError?.message||'Meta delivery failed').slice(0,500),metadata:{...(job.metadata||{}),whatsapp_fallback:{at:eventAt,reason:'delivery_failed',provider_message_id:mid}},updated_at:new Date().toISOString()}).eq('id',job.id);processed++}return processed}

async function webhook(req:Request,raw:string){let payload:any;try{payload=JSON.parse(raw)}catch{return json({error:'invalid_json'},400)}if(payload?.object!=='whatsapp_business_account')return json({ignored:true});const ids=new Set<string>();for(const e of payload?.entry||[])for(const c of e?.changes||[]){const id=c?.value?.metadata?.phone_number_id;if(id)ids.add(String(id))}if(!ids.size)return json({ignored:true});const{data:configs,error:ce}=await supabase.from('appointment_communication_channel_settings').select('tenant_id,whatsapp_phone_number_id,whatsapp_app_secret_env,whatsapp_access_token_env,whatsapp_graph_version').in('whatsapp_phone_number_id',Array.from(ids));if(ce||!configs?.length)return json({error:'provider_config_not_found'},404);const sig=req.headers.get('x-hub-signature-256')||'';let valid=false;for(const c of configs){const secret=Deno.env.get(c.whatsapp_app_secret_env)||'';if(secret&&timingSafeEqual(`sha256=${await hmacSha256Hex(secret,raw)}`,sig)){valid=true;break}}if(!valid)return json({error:'invalid_signature'},401);let processed=0,inbound=0;for(const e of payload?.entry||[])for(const ch of e?.changes||[]){const phoneId=String(ch?.value?.metadata?.phone_number_id||''),config=(configs as MetaConfig[]).find(c=>c.whatsapp_phone_number_id===phoneId);if(!config)continue;processed+=await processStatuses(config,ch?.value);for(const message of ch?.value?.messages||[])if(await processInbound(config,message))inbound++}return json({received:true,processed_statuses:processed,processed_inbound:inbound})}

Deno.serve(async(req:Request)=>{try{const url=new URL(req.url);if(req.method==='GET')return verifyWebhook(url);if(req.method!=='POST')return new Response('Method Not Allowed',{status:405});const raw=await req.text();let body:any={};try{body=raw?JSON.parse(raw):{}}catch{}if(body?.action==='dispatch')return dispatch(req,body);return webhook(req,raw)}catch(e){console.error('appointment-whatsapp-meta',e);return json({error:'internal_error'},500)}})
