import Link from 'next/link'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { createSupabaseServerClient } from '@/lib/supabase-server'

export const dynamic='force-dynamic'
async function viewer(){const supabase=createSupabaseServerClient(cookies());const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const{data:p}=await supabase.from('profiles').select('tenant_id,role').eq('user_id',user.id).maybeSingle();if(!p?.tenant_id||!['admin','nutritionist','nutri'].includes(String(p.role||'').toLowerCase()))redirect('/patient/home');return{supabase,tenantId:p.tenant_id}}
async function saveStage(f:FormData){'use server';const{supabase,tenantId}=await viewer();const id=String(f.get('id')||''),name=String(f.get('name')||'').trim().slice(0,80),sort=Math.max(1,Math.min(999,Number(f.get('sort_order')||100))),active=f.get('active')==='on';if(!id||!name)redirect('/admin/crm/stages?error=invalid');const{error}=await supabase.from('crm_stages').update({name,sort_order:sort,active,updated_at:new Date().toISOString()}).eq('id',id).eq('tenant_id',tenantId);if(error)redirect('/admin/crm/stages?error=save');revalidatePath('/admin/crm');revalidatePath('/admin/crm/stages');redirect('/admin/crm/stages?saved=1')}
async function createStage(f:FormData){'use server';const{supabase,tenantId}=await viewer();const name=String(f.get('name')||'').trim().slice(0,80),sort=Math.max(1,Math.min(999,Number(f.get('sort_order')||100)));if(!name)redirect('/admin/crm/stages?error=invalid');const{error}=await supabase.from('crm_stages').insert({tenant_id:tenantId,code:`custom_${Date.now().toString(36)}`,name,sort_order:sort,category:'custom',active:true,is_system:false});if(error)redirect('/admin/crm/stages?error=save');revalidatePath('/admin/crm');revalidatePath('/admin/crm/stages');redirect('/admin/crm/stages?saved=1')}
async function saveRule(f:FormData){'use server';const{supabase,tenantId}=await viewer();const id=String(f.get('id')||''),stage=String(f.get('stage_id')||''),value=String(f.get('source_value')||'').trim(),priority=Math.max(1,Math.min(9999,Number(f.get('priority')||100))),active=f.get('active')==='on';const{data:s}=await supabase.from('crm_stages').select('id').eq('tenant_id',tenantId).eq('id',stage).maybeSingle();if(!id||!value||!s)redirect('/admin/crm/stages?error=rule');const{error}=await supabase.from('crm_stage_mapping_rules').update({source_value:value,stage_id:stage,priority,active,updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('id',id);if(error)redirect('/admin/crm/stages?error=rule');revalidatePath('/admin/crm/stages');redirect('/admin/crm/stages?saved=1')}
async function createRule(f:FormData){'use server';const{supabase,tenantId}=await viewer();const kind=String(f.get('source_kind')||''),value=String(f.get('source_value')||'').trim(),stage=String(f.get('stage_id')||''),priority=Math.max(1,Math.min(9999,Number(f.get('priority')||100)));if(!['lifecycle','operational','default'].includes(kind)||!value||!stage)redirect('/admin/crm/stages?error=rule');const{data:s}=await supabase.from('crm_stages').select('id').eq('tenant_id',tenantId).eq('id',stage).maybeSingle();if(!s)redirect('/admin/crm/stages?error=rule');const{error}=await supabase.from('crm_stage_mapping_rules').insert({tenant_id:tenantId,source_kind:kind,source_value:value,stage_id:stage,priority,active:true});if(error)redirect('/admin/crm/stages?error=rule');revalidatePath('/admin/crm/stages');redirect('/admin/crm/stages?saved=1')}
export default async function Page({searchParams}:{searchParams?:{saved?:string;error?:string}}){const{supabase,tenantId}=await viewer();const[{data:stages},{data:rules}]=await Promise.all([supabase.from('crm_stages').select('id,code,name,sort_order,category,active,is_system').eq('tenant_id',tenantId).order('sort_order'),supabase.from('crm_stage_mapping_rules').select('*').eq('tenant_id',tenantId).order('priority')]);const stageMap=new Map((stages||[]).map((s:any)=>[s.id,s.name]));return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900"><div className="mx-auto max-w-5xl space-y-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-amber-700">CRM</p><h1 className="text-3xl font-black">Etapas e regras de entrada</h1><p className="mt-2 text-sm text-slate-600">Edite as etapas e também como sinais da jornada do app entram no CRM. Menor prioridade vence.</p></div><Link href="/admin/crm" className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">Voltar</Link></div>{searchParams?.saved==='1'&&<div className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">Configuração salva.</div>}{searchParams?.error&&<div className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-800">Não foi possível salvar. Revise os dados.</div>}
<section className="space-y-3"><h2 className="text-xl font-black">Etapas</h2>{(stages||[]).map((s:any)=><form key={s.id} action={saveStage} className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm md:grid-cols-[1fr_120px_auto_auto]"><input type="hidden" name="id" value={s.id}/><label className="grid gap-1 text-sm font-bold"><span>Nome</span><input name="name" defaultValue={s.name} className="rounded-xl border px-3 py-2"/></label><label className="grid gap-1 text-sm font-bold"><span>Ordem</span><input name="sort_order" type="number" min={1} max={999} defaultValue={s.sort_order} className="rounded-xl border px-3 py-2"/></label><label className="flex items-end gap-2 pb-2 text-sm font-bold"><input name="active" type="checkbox" defaultChecked={s.active}/>Ativa</label><div className="flex items-end"><button className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-black text-white">Salvar</button></div><div className="md:col-span-4 text-xs text-slate-500">{s.is_system?'Etapa de sistema':'Etapa personalizada'} · código {s.code}</div></form>)}</section>
<form action={createStage} className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-lg font-black">Nova etapa personalizada</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr_120px_auto]"><input name="name" placeholder="Ex.: Aguardando decisão" className="rounded-xl border bg-white px-3 py-2"/><input name="sort_order" type="number" min={1} max={999} defaultValue={60} className="rounded-xl border bg-white px-3 py-2"/><button className="rounded-xl bg-amber-300 px-4 py-2 text-sm font-black">Criar etapa</button></div></form>
<section className="space-y-3"><div><h2 className="text-xl font-black">Regras App → CRM</h2><p className="text-sm text-slate-600">Ex.: jornada “reactivation” → etapa Reativação. Você pode alterar, desativar ou criar novas regras sem deploy.</p></div>{(rules||[]).map((r:any)=><form action={saveRule} key={r.id} className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[140px_1fr_1fr_100px_auto_auto]"><input type="hidden" name="id" value={r.id}/><div><div className="text-xs font-bold uppercase text-slate-400">Tipo</div><div className="text-sm font-black">{r.source_kind}</div></div><input name="source_value" defaultValue={r.source_value} className="rounded-xl border px-3 py-2 text-sm"/><select name="stage_id" defaultValue={r.stage_id} className="rounded-xl border px-3 py-2 text-sm">{(stages||[]).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="priority" type="number" min={1} max={9999} defaultValue={r.priority} className="rounded-xl border px-3 py-2 text-sm"/><label className="flex items-center gap-2 text-sm font-bold"><input name="active" type="checkbox" defaultChecked={r.active}/>Ativa</label><button className="rounded-xl bg-slate-900 px-3 py-2 text-sm font-black text-white">Salvar</button><div className="md:col-span-6 text-xs text-slate-400">Destino atual: {stageMap.get(r.stage_id)||'—'}</div></form>)}</section>
<form action={createRule} className="rounded-3xl border border-blue-200 bg-blue-50 p-5"><h2 className="text-lg font-black">Nova regra automática</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><select name="source_kind" className="rounded-xl border bg-white px-3 py-2"><option value="lifecycle">Estado da jornada</option><option value="operational">Estado operacional</option><option value="default">Fallback</option></select><input name="source_value" placeholder="Ex.: plan_expired ou *" className="rounded-xl border bg-white px-3 py-2"/><select name="stage_id" className="rounded-xl border bg-white px-3 py-2">{(stages||[]).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input name="priority" type="number" min={1} max={9999} defaultValue={100} className="rounded-xl border bg-white px-3 py-2"/></div><button className="mt-3 rounded-xl bg-blue-700 px-4 py-2 text-sm font-black text-white">Criar regra</button></form></div></main>}
