import Link from 'next/link'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { createSupabaseServerClient } from '@/lib/supabase-server'

export const dynamic='force-dynamic'

async function viewer(){const supabase=createSupabaseServerClient(cookies());const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const{data:profile}=await supabase.from('profiles').select('tenant_id,role').eq('user_id',user.id).maybeSingle();const role=String(profile?.role||'').toLowerCase();if(!profile?.tenant_id||!['admin','nutritionist','nutri'].includes(role))redirect('/patient/home');return{supabase,user,tenantId:profile.tenant_id}}

async function saveStage(formData:FormData){'use server';const{supabase,tenantId}=await viewer();const id=String(formData.get('id')||'');const name=String(formData.get('name')||'').trim().slice(0,80);const sort=Math.max(1,Math.min(999,Number(formData.get('sort_order')||100)));const active=formData.get('active')==='on';if(!id||!name)redirect('/admin/crm/stages?error=invalid');const{error}=await supabase.from('crm_stages').update({name,sort_order:sort,active,updated_at:new Date().toISOString()}).eq('id',id).eq('tenant_id',tenantId);if(error)redirect('/admin/crm/stages?error=save');revalidatePath('/admin/crm');revalidatePath('/admin/crm/stages');redirect('/admin/crm/stages?saved=1')}

async function createStage(formData:FormData){'use server';const{supabase,tenantId}=await viewer();const name=String(formData.get('name')||'').trim().slice(0,80);const sort=Math.max(1,Math.min(999,Number(formData.get('sort_order')||100)));if(!name)redirect('/admin/crm/stages?error=invalid');const code=`custom_${Date.now().toString(36)}`;const{error}=await supabase.from('crm_stages').insert({tenant_id:tenantId,code,name,sort_order:sort,category:'custom',active:true,is_system:false});if(error)redirect('/admin/crm/stages?error=save');revalidatePath('/admin/crm');revalidatePath('/admin/crm/stages');redirect('/admin/crm/stages?saved=1')}

export default async function CrmStagesPage({searchParams}:{searchParams?:{saved?:string;error?:string}}){const{supabase,tenantId}=await viewer();const{data:stages}=await supabase.from('crm_stages').select('id,code,name,sort_order,category,active,is_system').eq('tenant_id',tenantId).order('sort_order');return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-900"><div className="mx-auto max-w-4xl space-y-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">CRM</p><h1 className="text-3xl font-black">Etapas configuráveis</h1><p className="mt-2 text-sm text-slate-600">Renomeie, reordene ou desative etapas. Etapas de sistema mantêm o código interno para o motor, mas o nome exibido é seu.</p></div><Link href="/admin/crm" className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-bold">Voltar</Link></div>{searchParams?.saved==='1'&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-800">Etapa salva.</div>}{searchParams?.error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-800">Não foi possível salvar. Revise os dados.</div>}
<section className="space-y-3">{(stages||[]).map((s:any)=><form key={s.id} action={saveStage} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_120px_auto_auto]"><input type="hidden" name="id" value={s.id}/><label className="grid gap-1 text-sm font-bold"><span>Nome</span><input name="name" defaultValue={s.name} className="rounded-xl border border-slate-300 px-3 py-2"/></label><label className="grid gap-1 text-sm font-bold"><span>Ordem</span><input name="sort_order" type="number" min={1} max={999} defaultValue={s.sort_order} className="rounded-xl border border-slate-300 px-3 py-2"/></label><label className="flex items-end gap-2 pb-2 text-sm font-bold"><input name="active" type="checkbox" defaultChecked={s.active}/>Ativa</label><div className="flex items-end"><button className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-black text-white">Salvar</button></div><div className="md:col-span-4 text-xs text-slate-500">{s.is_system?'Etapa de sistema':'Etapa personalizada'} · código {s.code}</div></form>)}</section>
<form action={createStage} className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-lg font-black">Nova etapa personalizada</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr_120px_auto]"><input name="name" placeholder="Ex.: Aguardando decisão" className="rounded-xl border border-amber-300 bg-white px-3 py-2"/><input name="sort_order" type="number" min={1} max={999} defaultValue={60} className="rounded-xl border border-amber-300 bg-white px-3 py-2"/><button className="rounded-xl bg-amber-300 px-4 py-2 text-sm font-black text-slate-950">Criar etapa</button></div></form></div></main>}
