import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import Link from 'next/link'
import { createSupabaseServerClient } from '@/lib/supabase-server'

export const dynamic='force-dynamic'
export const revalidate=0
const STAFF=['admin','nutritionist','nutri']

type Field={category:string;provider:string;key:string;label:string;description:string;type:'secret'|'text'|'url'|'boolean'|'json';required?:boolean;placeholder?:string}
type Group={id:string;title:string;subtitle:string;icon:string;fields:Field[]}

const GROUPS:Group[]=[
 {id:'whatsapp',title:'WhatsApp · Meta Cloud API',subtitle:'Confirmações, lembretes e atendimento bidirecional da agenda.',icon:'WA',fields:[
  {category:'Comunicação',provider:'meta_whatsapp',key:'PHONE_NUMBER_ID',label:'Phone Number ID',description:'ID do número cadastrado no WhatsApp Business Platform.',type:'text',required:true},
  {category:'Comunicação',provider:'meta_whatsapp',key:'WABA_ID',label:'WABA ID',description:'ID da conta WhatsApp Business.',type:'text',required:true},
  {category:'Comunicação',provider:'meta_whatsapp',key:'GRAPH_VERSION',label:'Graph API',description:'Versão da Graph API utilizada pelo adapter.',type:'text',placeholder:'v26.0'},
  {category:'Comunicação',provider:'meta_whatsapp',key:'ACCESS_TOKEN',label:'Access Token permanente',description:'Token de System User. Armazenado somente no Vault.',type:'secret',required:true},
  {category:'Comunicação',provider:'meta_whatsapp',key:'WEBHOOK_VERIFY_TOKEN',label:'Webhook Verify Token',description:'Token usado na verificação inicial do webhook Meta.',type:'secret',required:true},
  {category:'Comunicação',provider:'meta_whatsapp',key:'APP_SECRET',label:'App Secret',description:'Assina e valida eventos recebidos da Meta.',type:'secret',required:true},
 ]},
 {id:'webdiet',title:'WebDiet',subtitle:'Integração clínica, pacientes e dados nutricionais.',icon:'WD',fields:[
  {category:'Integrações clínicas',provider:'webdiet',key:'CLIENT_ID',label:'Client ID',description:'Identificador da conta/API WebDiet.',type:'text',required:true},
  {category:'Integrações clínicas',provider:'webdiet',key:'CLIENT_SECRET',label:'Client Secret',description:'Credencial confidencial da API WebDiet.',type:'secret',required:true},
  {category:'Integrações clínicas',provider:'webdiet',key:'BASE_URL',label:'Base URL',description:'Endpoint-base da API quando aplicável.',type:'url',placeholder:'https://...'},
 ]},
 {id:'openai',title:'Inteligência Artificial',subtitle:'Modelos, agentes e geração de conteúdo.',icon:'AI',fields:[
  {category:'Inteligência Artificial',provider:'openai',key:'API_KEY',label:'OpenAI API Key',description:'Chave privada para chamadas de IA do servidor.',type:'secret',required:true},
  {category:'Inteligência Artificial',provider:'openai',key:'MODEL',label:'Modelo padrão',description:'Modelo utilizado quando o recurso não definir um modelo específico.',type:'text',placeholder:'gpt-5.6'},
 ]},
 {id:'email',title:'E-mail transacional',subtitle:'Confirmações, alertas e mensagens operacionais.',icon:'@',fields:[
  {category:'Comunicação',provider:'resend',key:'API_KEY',label:'Resend API Key',description:'Chave privada do provedor de e-mail.',type:'secret'},
  {category:'Comunicação',provider:'resend',key:'FROM_EMAIL',label:'E-mail remetente',description:'Remetente padrão autorizado no provedor.',type:'text',placeholder:'contato@seudominio.com.br'},
 ]},
 {id:'stripe',title:'Pagamentos · Stripe',subtitle:'Checkout, assinaturas e webhooks financeiros.',icon:'$',fields:[
  {category:'Financeiro',provider:'stripe',key:'SECRET_KEY',label:'Secret Key',description:'Chave privada da conta Stripe.',type:'secret'},
  {category:'Financeiro',provider:'stripe',key:'PUBLISHABLE_KEY',label:'Publishable Key',description:'Chave pública utilizada no checkout.',type:'text'},
  {category:'Financeiro',provider:'stripe',key:'WEBHOOK_SECRET',label:'Webhook Secret',description:'Segredo de assinatura dos webhooks Stripe.',type:'secret'},
 ]},
 {id:'automation',title:'Automação e Webhooks',subtitle:'Conectores externos, n8n e endpoints auxiliares.',icon:'<>',fields:[
  {category:'Automação',provider:'automation',key:'N8N_BASE_URL',label:'n8n Base URL',description:'URL-base da sua instância de automação.',type:'url'},
  {category:'Automação',provider:'automation',key:'N8N_API_KEY',label:'n8n API Key',description:'Credencial privada quando a automação exigir autenticação.',type:'secret'},
  {category:'Automação',provider:'automation',key:'OUTBOUND_WEBHOOK_URL',label:'Webhook operacional',description:'Endpoint opcional para integrações personalizadas.',type:'url'},
 ]},
]

async function viewer(){const supabase=createSupabaseServerClient(cookies());const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login');const{data:p}=await supabase.from('profiles').select('tenant_id,role,name').eq('user_id',user.id).maybeSingle();if(!p?.tenant_id||!STAFF.includes(String(p.role||'').toLowerCase()))redirect('/patient/home');return{supabase,tenantId:p.tenant_id,userId:user.id,name:p.name||user.email||'Admin'}}

async function saveSetting(form:FormData){'use server';const{supabase}=await viewer();const value=String(form.get('value')||'');const type=String(form.get('type')||'text');if(type==='secret'&&!value)redirect('/admin/settings/vital?error=empty_secret');const{error}=await supabase.rpc('upsert_tenant_vital_setting',{p_category:String(form.get('category')||'Geral'),p_provider:String(form.get('provider')||''),p_setting_key:String(form.get('key')||''),p_label:String(form.get('label')||''),p_description:String(form.get('description')||''),p_value_type:type,p_value:value,p_required:form.get('required')==='true',p_enabled:true});if(error)redirect('/admin/settings/vital?error=save');revalidatePath('/admin/settings/vital');redirect('/admin/settings/vital?saved=1')}

async function saveCustom(form:FormData){'use server';const{supabase}=await viewer();const provider=String(form.get('provider')||'custom').trim().toLowerCase().replace(/[^a-z0-9_-]/g,'_');const key=String(form.get('key')||'').trim().toUpperCase().replace(/[^A-Z0-9_.-]/g,'_');const type=String(form.get('type')||'secret');const value=String(form.get('value')||'');if(provider.length<2||key.length<2||!value)redirect('/admin/settings/vital?error=custom');const{error}=await supabase.rpc('upsert_tenant_vital_setting',{p_category:'Personalizada',p_provider:provider,p_setting_key:key,p_label:String(form.get('label')||key).trim(),p_description:String(form.get('description')||''),p_value_type:type,p_value:value,p_required:false,p_enabled:true});if(error)redirect('/admin/settings/vital?error=custom');revalidatePath('/admin/settings/vital');redirect('/admin/settings/vital?saved=custom')}

function statusClass(status:string){return status==='valid'?'bg-emerald-50 text-emerald-700 border-emerald-200':status==='configured'?'bg-amber-50 text-amber-800 border-amber-200':status==='invalid'?'bg-red-50 text-red-700 border-red-200':'bg-slate-50 text-slate-600 border-slate-200'}
function statusLabel(status:string){return status==='valid'?'Validado':status==='configured'?'Configurado':status==='invalid'?'Inválido':status==='needs_review'?'Revisar':'Ausente'}

export default async function VitalSettings({searchParams}:{searchParams?:{saved?:string;error?:string}}){const{supabase,tenantId,name}=await viewer();const[{data:rows},{data:tenant},{data:channel}]=await Promise.all([supabase.from('tenant_vital_settings').select('provider,setting_key,label,value_type,config_value,required,enabled,validation_status,last_validated_at,updated_at').eq('tenant_id',tenantId),supabase.from('tenants').select('brand_name,slug,plan_tier').eq('id',tenantId).maybeSingle(),supabase.from('appointment_communication_channel_settings').select('whatsapp_activation_state,whatsapp_pilot_mode').eq('tenant_id',tenantId).maybeSingle()]);const map=new Map((rows||[]).map((r:any)=>[`${r.provider}:${r.setting_key}`,r]));const catalogKeys=new Set(GROUPS.flatMap(g=>g.fields.map(f=>`${f.provider}:${f.key}`)));const custom=(rows||[]).filter((r:any)=>!catalogKeys.has(`${r.provider}:${r.setting_key}`));const total=GROUPS.flatMap(g=>g.fields).filter(f=>f.required).length;const configured=GROUPS.flatMap(g=>g.fields).filter(f=>f.required&&map.has(`${f.provider}:${f.key}`)).length;return <main className="min-h-screen bg-[#F6F2EA] text-[#2B1A10]"><div className="mx-auto max-w-7xl px-5 py-8">
 <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#A78628]">Admin · Segurança operacional</p><h1 className="mt-1 text-3xl font-black">Configurações vitais</h1><p className="mt-1 max-w-3xl text-sm text-[#2B1A10]/60">Central única para credenciais, integrações e parâmetros que mantêm o sistema funcionando. Segredos são criptografados no Supabase Vault e nunca são exibidos novamente.</p></div><div className="flex gap-2"><Link href="/admin" className="rounded-xl border border-[#2B1A10]/15 bg-white px-4 py-2 text-sm font-bold">Voltar ao Admin</Link><Link href="/admin/appointments/communications/whatsapp/go-live" className="rounded-xl bg-[#2B1A10] px-4 py-2 text-sm font-bold text-white">Go-live WhatsApp</Link></div></div>
 {searchParams?.saved&&<div className="mb-4 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">Configuração salva com segurança.</div>}{searchParams?.error&&<div className="mb-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-800">Não foi possível salvar. Revise os dados e tente novamente.</div>}
 <section className="mb-6 grid gap-4 lg:grid-cols-[320px_1fr]"><div className="overflow-hidden rounded-3xl border border-[#2B1A10]/10 bg-white shadow-sm"><div className="h-28 bg-[#2B1A10] p-5 text-white"><p className="text-xs font-black uppercase tracking-[.2em] text-[#E6CF83]">Conta</p><p className="mt-3 text-xl font-black">{tenant?.brand_name||'Minha clínica'}</p></div><div className="p-5"><p className="text-sm font-black">{name}</p><p className="mt-4 text-xs font-bold uppercase tracking-wide text-[#2B1A10]/45">Plano</p><p className="text-sm">{tenant?.plan_tier||'—'}</p><p className="mt-3 text-xs font-bold uppercase tracking-wide text-[#2B1A10]/45">Identificador</p><p className="break-all font-mono text-[11px] text-[#2B1A10]/60">{tenantId}</p><p className="mt-3 text-xs font-bold uppercase tracking-wide text-[#2B1A10]/45">WhatsApp</p><p className="text-sm font-bold">{channel?.whatsapp_activation_state||'draft'} {channel?.whatsapp_pilot_mode?'· piloto':''}</p></div></div>
 <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-3xl border border-[#2B1A10]/10 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wide text-[#2B1A10]/45">Prontidão essencial</p><p className="mt-2 text-4xl font-black">{configured}/{total}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#2B1A10]/10"><div className="h-full bg-[#C9A435]" style={{width:`${total?configured/total*100:0}%`}}/></div></div><div className="rounded-3xl border border-[#2B1A10]/10 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wide text-[#2B1A10]/45">Segredos protegidos</p><p className="mt-2 text-4xl font-black">{(rows||[]).filter((r:any)=>r.value_type==='secret').length}</p><p className="mt-3 text-sm text-[#2B1A10]/55">Valores permanecem apenas no Vault.</p></div><div className="rounded-3xl border border-[#2B1A10]/10 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wide text-[#2B1A10]/45">Integrações</p><p className="mt-2 text-4xl font-black">{GROUPS.filter(g=>g.fields.some(f=>map.has(`${f.provider}:${f.key}`))).length}/{GROUPS.length}</p><p className="mt-3 text-sm text-[#2B1A10]/55">Com pelo menos uma configuração cadastrada.</p></div></div></section>
 <div className="space-y-5">{GROUPS.map(g=>{const groupConfigured=g.fields.filter(f=>map.has(`${f.provider}:${f.key}`)).length;return <section key={g.id} className="rounded-3xl border border-[#2B1A10]/10 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#C9A435]/15 font-black text-[#8A6B16]">{g.icon}</div><div><h2 className="text-lg font-black">{g.title}</h2><p className="text-sm text-[#2B1A10]/55">{g.subtitle}</p></div></div><span className="rounded-full border border-[#2B1A10]/10 bg-[#F6F2EA] px-3 py-1 text-xs font-black">{groupConfigured}/{g.fields.length} configurados</span></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{g.fields.map(f=>{const r:any=map.get(`${f.provider}:${f.key}`);return <form action={saveSetting} key={`${f.provider}:${f.key}`} className="rounded-2xl border border-[#2B1A10]/10 bg-[#FCFAF6] p-4"><input type="hidden" name="category" value={f.category}/><input type="hidden" name="provider" value={f.provider}/><input type="hidden" name="key" value={f.key}/><input type="hidden" name="label" value={f.label}/><input type="hidden" name="description" value={f.description}/><input type="hidden" name="type" value={f.type}/><input type="hidden" name="required" value={String(Boolean(f.required))}/><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black">{f.label}{f.required&&<span className="ml-1 text-red-500">*</span>}</p><p className="mt-1 text-xs leading-relaxed text-[#2B1A10]/50">{f.description}</p></div><span className={`shrink-0 rounded-full border px-2 py-1 text-[10px] font-black ${statusClass(r?.validation_status||'unknown')}`}>{statusLabel(r?.validation_status||'unknown')}</span></div><div className="mt-3 flex gap-2"><input name="value" type={f.type==='secret'?'password':'text'} defaultValue={f.type==='secret'?'':(r?.config_value||f.placeholder||'')} placeholder={f.type==='secret'?(r?'•••••••••••• · digite para substituir':'Cole o segredo aqui'):(f.placeholder||'Digite o valor')} className="min-w-0 flex-1 rounded-xl border border-[#2B1A10]/15 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#C9A435]"/><button className="rounded-xl bg-[#2B1A10] px-4 py-2 text-xs font-black text-white">{r?'Atualizar':'Cadastrar'}</button></div>{r&&<p className="mt-2 text-[10px] text-[#2B1A10]/40">Última alteração: {new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(r.updated_at))}{f.type==='secret'?' · valor não recuperável pela interface':''}</p>}</form>})}</div></section>})}</div>
 <section className="mt-5 rounded-3xl border border-dashed border-[#C9A435]/60 bg-[#FFF9E8] p-5"><h2 className="text-lg font-black">Integração personalizada</h2><p className="mt-1 text-sm text-[#2B1A10]/55">Cadastre qualquer chave futura sem precisar alterar o banco. Use segredo para tokens, senhas e chaves privadas.</p><form action={saveCustom} className="mt-4 grid gap-3 md:grid-cols-5"><input name="provider" placeholder="provider (ex: make)" className="rounded-xl border bg-white px-3 py-2.5 text-sm"/><input name="key" placeholder="CHAVE_API" className="rounded-xl border bg-white px-3 py-2.5 text-sm"/><input name="label" placeholder="Nome amigável" className="rounded-xl border bg-white px-3 py-2.5 text-sm"/><select name="type" className="rounded-xl border bg-white px-3 py-2.5 text-sm"><option value="secret">Segredo</option><option value="text">Texto</option><option value="url">URL</option><option value="json">JSON</option></select><input name="value" type="password" placeholder="Valor" className="rounded-xl border bg-white px-3 py-2.5 text-sm"/><textarea name="description" placeholder="Para que esta chave serve?" className="md:col-span-4 rounded-xl border bg-white px-3 py-2.5 text-sm"/><button className="rounded-xl bg-[#C9A435] px-4 py-2.5 text-sm font-black text-[#2B1A10]">Salvar chave</button></form>{custom.length>0&&<div className="mt-4 flex flex-wrap gap-2">{custom.map((r:any)=><span key={`${r.provider}:${r.setting_key}`} className="rounded-full border border-[#C9A435]/30 bg-white px-3 py-1.5 text-xs font-bold">{r.provider} · {r.label} · {statusLabel(r.validation_status)}</span>)}</div>}</section>
 <div className="mt-6 rounded-2xl border border-[#2B1A10]/10 bg-white p-4 text-xs leading-relaxed text-[#2B1A10]/55"><b className="text-[#2B1A10]">Proteção deliberada:</b> esta central não aceita nem exibe a Service Role do Supabase, senhas de usuários ou outros segredos-raiz da infraestrutura. Esses itens permanecem fora do painel para reduzir o raio de impacto de uma conta administrativa comprometida.</div>
 </div></main>}
