-- Phase 2 audit hardening: snapshot correctness and phase-scoped criteria.

CREATE OR REPLACE FUNCTION public.refresh_patient_operational_snapshot(p_tenant_id uuid,p_reference_date date DEFAULT ((now() AT TIME ZONE 'America/Sao_Paulo'))::date)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path='public' AS $function$
DECLARE
  v_rows int:=0;v_calculated_at timestamptz:=((p_reference_date::timestamp+time '12:00') AT TIME ZONE 'America/Sao_Paulo');v_rules jsonb;
  v_gentle int;v_oscillating int;v_risk int;v_critical int;v_inactive int;v_adherence_risk numeric;v_adherence_oscillating numeric;v_checkin_overdue int;v_plan_expiring int;v_plan_urgent int;v_protocol_ending int;v_protocol_urgent int;
  v_inactivity_weight numeric;v_adherence_weight numeric;v_weight_total numeric;v_level_critical int;v_level_high int;v_level_medium int;
BEGIN
  IF p_tenant_id IS NULL THEN RAISE EXCEPTION 'tenant_id é obrigatório' USING ERRCODE='22023';END IF;
  v_rules:=public.get_followup_engine_rules(p_tenant_id);
  v_gentle:=COALESCE((v_rules#>>'{inactivity,gentle_days}')::int,2);v_oscillating:=COALESCE((v_rules#>>'{inactivity,oscillating_days}')::int,4);v_risk:=COALESCE((v_rules#>>'{inactivity,risk_days}')::int,7);v_critical:=COALESCE((v_rules#>>'{inactivity,critical_days}')::int,10);v_inactive:=COALESCE((v_rules#>>'{inactivity,inactive_days}')::int,14);
  v_adherence_risk:=COALESCE((v_rules#>>'{adherence,at_risk_below}')::numeric,40);v_adherence_oscillating:=COALESCE((v_rules#>>'{adherence,oscillating_below}')::numeric,60);v_checkin_overdue:=COALESCE((v_rules#>>'{checkin,overdue_days}')::int,8);v_plan_expiring:=COALESCE((v_rules#>>'{plan,expiring_days}')::int,15);v_plan_urgent:=COALESCE((v_rules#>>'{plan,urgent_days}')::int,7);v_protocol_ending:=COALESCE((v_rules#>>'{protocol,ending_days}')::int,7);v_protocol_urgent:=COALESCE((v_rules#>>'{protocol,urgent_days}')::int,3);
  v_inactivity_weight:=GREATEST(0,COALESCE((v_rules#>>'{risk_scoring,inactivity_weight}')::numeric,60));v_adherence_weight:=GREATEST(0,COALESCE((v_rules#>>'{risk_scoring,adherence_weight}')::numeric,40));v_weight_total:=v_inactivity_weight+v_adherence_weight;v_level_critical:=COALESCE((v_rules#>>'{risk_scoring,critical_min}')::int,75);v_level_high:=COALESCE((v_rules#>>'{risk_scoring,high_min}')::int,55);v_level_medium:=COALESCE((v_rules#>>'{risk_scoring,medium_min}')::int,30);
  IF NOT(v_gentle>=1 AND v_gentle<v_oscillating AND v_oscillating<v_risk AND v_risk<v_critical AND v_critical<v_inactive) THEN RAISE EXCEPTION 'Faixas de inatividade inválidas nas configurações do motor' USING ERRCODE='22023';END IF;
  IF v_weight_total<=0 OR NOT(v_level_critical>v_level_high AND v_level_high>v_level_medium AND v_level_critical<=100 AND v_level_medium>=0) THEN RAISE EXCEPTION 'Configuração de score de risco inválida' USING ERRCODE='22023';END IF;

  WITH patients AS (
    SELECT p.user_id,p.tenant_id,(p.created_at AT TIME ZONE 'America/Sao_Paulo')::date created_date,COALESCE(p.onboarding_completed,false) onboarding_completed,p.plan_expires_at,COALESCE(p.current_streak,0) current_streak
    FROM public.profiles p WHERE p.tenant_id=p_tenant_id AND p.role='patient'
  ), activity_all AS (
    SELECT dl.user_id,dl.log_date activity_date FROM public.daily_logs dl JOIN patients p ON p.user_id=dl.user_id
    UNION ALL SELECT cd.paciente_id,cd.data FROM public.checkin_diario cd JOIN patients p ON p.user_id=cd.paciente_id
    UNION ALL SELECT wr.user_id,(wr.created_at AT TIME ZONE 'America/Sao_Paulo')::date FROM public.weekly_checkin_responses wr JOIN patients p ON p.user_id=wr.user_id
    UNION ALL SELECT pa.user_id,pp.checkin_date FROM public.protocol_progress pp JOIN public.protocol_assignments pa ON pa.id=pp.assignment_id JOIN patients p ON p.user_id=pa.user_id
  ), activity_summary AS (SELECT user_id,max(activity_date) last_activity_date FROM activity_all GROUP BY user_id),
  activity_7 AS (
    SELECT x.user_id,count(DISTINCT x.activity_date)::int active_days_7d FROM (
      SELECT dl.user_id,dl.log_date activity_date FROM public.daily_logs dl JOIN patients p ON p.user_id=dl.user_id WHERE dl.log_date BETWEEN p_reference_date-6 AND p_reference_date
      UNION ALL SELECT cd.paciente_id,cd.data FROM public.checkin_diario cd JOIN patients p ON p.user_id=cd.paciente_id WHERE cd.data BETWEEN p_reference_date-6 AND p_reference_date
      UNION ALL SELECT wr.user_id,(wr.created_at AT TIME ZONE 'America/Sao_Paulo')::date FROM public.weekly_checkin_responses wr JOIN patients p ON p.user_id=wr.user_id WHERE (wr.created_at AT TIME ZONE 'America/Sao_Paulo')::date BETWEEN p_reference_date-6 AND p_reference_date
      UNION ALL SELECT pa.user_id,pp.checkin_date FROM public.protocol_progress pp JOIN public.protocol_assignments pa ON pa.id=pp.assignment_id JOIN patients p ON p.user_id=pa.user_id WHERE pp.checkin_date BETWEEN p_reference_date-6 AND p_reference_date
    ) x GROUP BY x.user_id
  ), weekly AS (SELECT p.user_id,max((wr.created_at AT TIME ZONE 'America/Sao_Paulo')::date) last_weekly_checkin_date FROM patients p LEFT JOIN public.weekly_checkin_responses wr ON wr.user_id=p.user_id GROUP BY p.user_id),
  appointment_base AS (
    SELECT p.user_id,min(a.scheduled_at) FILTER(WHERE a.scheduled_at >= (p_reference_date::timestamp AT TIME ZONE 'America/Sao_Paulo') AND a.status IN('scheduled','confirmed')) next_appointment_at,max(COALESCE(a.completed_at,a.scheduled_at)) FILTER(WHERE a.status='completed') last_appointment_at
    FROM patients p LEFT JOIN public.appointments a ON a.patient_id=p.user_id AND a.tenant_id=p.tenant_id GROUP BY p.user_id
  ), appointments AS (
    SELECT ab.user_id,ab.next_appointment_at,ab.last_appointment_at,COALESCE(bool_or(a.scheduled_at < (p_reference_date::timestamp AT TIME ZONE 'America/Sao_Paulo') AND a.status IN('scheduled','confirmed') AND (ab.last_appointment_at IS NULL OR a.scheduled_at>ab.last_appointment_at)),false) consultation_overdue
    FROM appointment_base ab LEFT JOIN public.appointments a ON a.patient_id=ab.user_id AND a.tenant_id=p_tenant_id GROUP BY ab.user_id,ab.next_appointment_at,ab.last_appointment_at
  ), protocols AS (SELECT p.user_id,min(pa.end_date) FILTER(WHERE pa.status='active' AND pa.end_date>=p_reference_date) active_protocol_end_date FROM patients p LEFT JOIN public.protocol_assignments pa ON pa.user_id=p.user_id GROUP BY p.user_id),
  base AS (
    SELECT p.*,a.last_activity_date,COALESCE(a7.active_days_7d,0) active_days_7d,GREATEST(1,LEAST(7,(p_reference_date-p.created_date)+1))::int eligible_days,COALESCE(p_reference_date-a.last_activity_date,p_reference_date-p.created_date) days_inactive,w.last_weekly_checkin_date,ap.next_appointment_at,ap.last_appointment_at,ap.consultation_overdue,pr.active_protocol_end_date
    FROM patients p LEFT JOIN activity_summary a ON a.user_id=p.user_id LEFT JOIN activity_7 a7 ON a7.user_id=p.user_id LEFT JOIN weekly w ON w.user_id=p.user_id LEFT JOIN appointments ap ON ap.user_id=p.user_id LEFT JOIN protocols pr ON pr.user_id=p.user_id
  ), scored AS (
    SELECT b.*,round((100.0*b.active_days_7d/NULLIF(b.eligible_days,0))::numeric,1) adherence_7d_calc,
      CASE WHEN b.days_inactive<v_gentle THEN 0 WHEN b.days_inactive<v_oscillating THEN 20 WHEN b.days_inactive<v_risk THEN 40 WHEN b.days_inactive<v_critical THEN 60 WHEN b.days_inactive<v_inactive THEN 80 ELSE 100 END inactivity_risk_calc,
      GREATEST(0,LEAST(100,round(100-(100.0*b.active_days_7d/NULLIF(b.eligible_days,0)))::int)) adherence_risk_calc,
      (b.onboarding_completed AND (b.last_weekly_checkin_date IS NULL OR p_reference_date-b.last_weekly_checkin_date>=v_checkin_overdue)) checkin_overdue_calc,
      (b.plan_expires_at IS NOT NULL AND (b.plan_expires_at AT TIME ZONE 'America/Sao_Paulo')::date BETWEEN p_reference_date AND p_reference_date+v_plan_expiring) plan_expiring_calc,
      (b.active_protocol_end_date IS NOT NULL AND b.active_protocol_end_date BETWEEN p_reference_date AND p_reference_date+v_protocol_ending) protocol_ending_calc
    FROM base b
  ), classified AS (
    SELECT s.*,round(((s.inactivity_risk_calc*v_inactivity_weight)+(s.adherence_risk_calc*v_adherence_weight))/v_weight_total)::int overall_risk_calc,
      CASE WHEN NOT s.onboarding_completed THEN 'onboarding' WHEN s.days_inactive>=v_inactive THEN 'inactive' WHEN s.days_inactive>=v_risk OR s.adherence_7d_calc<v_adherence_risk THEN 'at_risk' WHEN s.days_inactive>=v_oscillating OR s.adherence_7d_calc<v_adherence_oscillating THEN 'oscillating' ELSE 'adherent' END operational_status_calc,
      CASE WHEN s.days_inactive>=v_critical OR s.consultation_overdue THEN 'critical' WHEN s.days_inactive>=v_risk OR (s.plan_expiring_calc AND (s.plan_expires_at AT TIME ZONE 'America/Sao_Paulo')::date<=p_reference_date+v_plan_urgent) OR (s.protocol_ending_calc AND s.active_protocol_end_date<=p_reference_date+v_protocol_urgent) THEN 'today' WHEN s.days_inactive>=v_oscillating OR s.checkin_overdue_calc OR s.plan_expiring_calc OR s.protocol_ending_calc THEN 'this_week' WHEN s.days_inactive>=v_gentle AND s.days_inactive<v_oscillating THEN 'automatic' ELSE 'none' END attention_bucket_calc
    FROM scored s
  )
  INSERT INTO public.patient_risk_scores(tenant_id,user_id,overall_risk,inactivity_risk,adherence_risk,emotional_risk,engagement_risk,risk_level,signals,recommended_action,action_taken,days_since_activity,current_streak,adherence_7d,last_checkin_score,calculated_at,operational_status,attention_bucket,last_activity_date,eligible_activity_days,next_appointment_at,last_appointment_at,active_protocol_end_date,checkin_overdue,consultation_overdue,plan_expiring,protocol_ending,reasons)
  SELECT c.tenant_id,c.user_id,c.overall_risk_calc,c.inactivity_risk_calc,c.adherence_risk_calc,0,GREATEST(c.inactivity_risk_calc,c.adherence_risk_calc),CASE WHEN c.overall_risk_calc>=v_level_critical THEN 'critical' WHEN c.overall_risk_calc>=v_level_high THEN 'high' WHEN c.overall_risk_calc>=v_level_medium THEN 'medium' ELSE 'low' END,
    jsonb_build_object('days_since_activity',c.days_inactive,'adherence_7d',c.adherence_7d_calc,'checkin_overdue',c.checkin_overdue_calc,'consultation_overdue',c.consultation_overdue,'plan_expiring',c.plan_expiring_calc,'protocol_ending',c.protocol_ending_calc,'risk_scoring',v_rules->'risk_scoring'),
    CASE c.attention_bucket_calc WHEN 'critical' THEN 'Revisar hoje e definir intervenção humana.' WHEN 'today' THEN 'Priorizar contato ou revisão hoje.' WHEN 'this_week' THEN 'Revisar nesta semana.' WHEN 'automatic' THEN 'Elegível para lembrete leve automático.' ELSE 'Sem intervenção necessária.' END,false,c.days_inactive,c.current_streak,c.adherence_7d_calc,NULL,v_calculated_at,c.operational_status_calc,c.attention_bucket_calc,c.last_activity_date,c.eligible_days,c.next_appointment_at,c.last_appointment_at,c.active_protocol_end_date,c.checkin_overdue_calc,c.consultation_overdue,c.plan_expiring_calc,c.protocol_ending_calc,
    (CASE WHEN c.days_inactive>=v_oscillating THEN jsonb_build_array(jsonb_build_object('code','inactivity','days',c.days_inactive)) ELSE '[]'::jsonb END)||(CASE WHEN c.checkin_overdue_calc THEN jsonb_build_array(jsonb_build_object('code','checkin_overdue')) ELSE '[]'::jsonb END)||(CASE WHEN c.consultation_overdue THEN jsonb_build_array(jsonb_build_object('code','consultation_overdue')) ELSE '[]'::jsonb END)||(CASE WHEN c.plan_expiring_calc THEN jsonb_build_array(jsonb_build_object('code','plan_expiring','date',(c.plan_expires_at AT TIME ZONE 'America/Sao_Paulo')::date)) ELSE '[]'::jsonb END)||(CASE WHEN c.protocol_ending_calc THEN jsonb_build_array(jsonb_build_object('code','protocol_ending','date',c.active_protocol_end_date)) ELSE '[]'::jsonb END)
  FROM classified c
  ON CONFLICT(user_id,calculated_date) DO UPDATE SET tenant_id=EXCLUDED.tenant_id,overall_risk=EXCLUDED.overall_risk,inactivity_risk=EXCLUDED.inactivity_risk,adherence_risk=EXCLUDED.adherence_risk,emotional_risk=EXCLUDED.emotional_risk,engagement_risk=EXCLUDED.engagement_risk,risk_level=EXCLUDED.risk_level,signals=EXCLUDED.signals,recommended_action=EXCLUDED.recommended_action,action_taken=false,days_since_activity=EXCLUDED.days_since_activity,current_streak=EXCLUDED.current_streak,adherence_7d=EXCLUDED.adherence_7d,calculated_at=EXCLUDED.calculated_at,operational_status=EXCLUDED.operational_status,attention_bucket=EXCLUDED.attention_bucket,last_activity_date=EXCLUDED.last_activity_date,eligible_activity_days=EXCLUDED.eligible_activity_days,next_appointment_at=EXCLUDED.next_appointment_at,last_appointment_at=EXCLUDED.last_appointment_at,active_protocol_end_date=EXCLUDED.active_protocol_end_date,checkin_overdue=EXCLUDED.checkin_overdue,consultation_overdue=EXCLUDED.consultation_overdue,plan_expiring=EXCLUDED.plan_expiring,protocol_ending=EXCLUDED.protocol_ending,reasons=EXCLUDED.reasons;
  GET DIAGNOSTICS v_rows=ROW_COUNT;RETURN v_rows;
END;$function$;

CREATE OR REPLACE FUNCTION public.refresh_patient_lifecycle_states(p_tenant_id uuid,p_reference_date date DEFAULT ((now() AT TIME ZONE 'America/Sao_Paulo'))::date)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path='public' AS $function$
DECLARE v_rules jsonb;v_enabled boolean;v_return_days int;v_reactivation_days int;v_protocol_window int;v_plan_grace int;v_rows int:=0;v_manual int:=0;
BEGIN
  v_rules:=public.get_followup_engine_rules(p_tenant_id);v_enabled:=COALESCE((v_rules#>>'{lifecycle,enabled}')::boolean,true);v_return_days:=GREATEST(1,COALESCE((v_rules#>>'{lifecycle,return_overdue_days}')::int,45));v_reactivation_days:=GREATEST(1,COALESCE((v_rules#>>'{lifecycle,reactivation_after_days}')::int,30));v_protocol_window:=GREATEST(0,COALESCE((v_rules#>>'{lifecycle,protocol_completed_window_days}')::int,7));v_plan_grace:=GREATEST(0,COALESCE((v_rules#>>'{lifecycle,plan_expired_grace_days}')::int,0));
  IF NOT v_enabled THEN
    UPDATE public.patient_risk_scores rs SET lifecycle_status=o.override_status,lifecycle_next_action=o.next_action,lifecycle_details=jsonb_build_object('source','manual_override','override_note',o.note)
    FROM public.patient_lifecycle_overrides o WHERE rs.tenant_id=p_tenant_id AND rs.calculated_date=p_reference_date AND o.tenant_id=p_tenant_id AND o.user_id=rs.user_id AND o.active=true;GET DIAGNOSTICS v_manual=ROW_COUNT;
    UPDATE public.patient_risk_scores rs SET lifecycle_status=NULL,lifecycle_next_action=NULL,lifecycle_details='{}'::jsonb WHERE rs.tenant_id=p_tenant_id AND rs.calculated_date=p_reference_date AND NOT EXISTS(SELECT 1 FROM public.patient_lifecycle_overrides o WHERE o.tenant_id=p_tenant_id AND o.user_id=rs.user_id AND o.active=true);GET DIAGNOSTICS v_rows=ROW_COUNT;RETURN v_rows+v_manual;
  END IF;
  WITH latest_protocol AS (
    SELECT DISTINCT ON(pa.user_id) pa.user_id,pa.status,pa.end_date,pa.progress_percentage,CASE WHEN (lower(COALESCE(pa.status,'')) IN('completed','concluido','concluído','finished') OR COALESCE(pa.progress_percentage,0)>=100) THEN pa.end_date ELSE NULL END completion_date
    FROM public.protocol_assignments pa JOIN public.profiles p ON p.user_id=pa.user_id AND p.tenant_id=p_tenant_id ORDER BY pa.user_id,COALESCE(pa.end_date,pa.start_date) DESC NULLS LAST,pa.created_at DESC
  ), overrides AS (SELECT * FROM public.patient_lifecycle_overrides WHERE tenant_id=p_tenant_id AND active=true),
  base AS (SELECT rs.id,rs.user_id,rs.days_since_activity,rs.next_appointment_at,rs.last_appointment_at,rs.consultation_overdue,rs.plan_expiring,p.plan_expires_at,p.onboarding_completed,lp.status protocol_status,lp.end_date protocol_end_date,lp.progress_percentage,lp.completion_date,o.override_status,o.next_action override_next_action,o.note override_note FROM public.patient_risk_scores rs JOIN public.profiles p ON p.user_id=rs.user_id AND p.tenant_id=rs.tenant_id LEFT JOIN latest_protocol lp ON lp.user_id=rs.user_id LEFT JOIN overrides o ON o.user_id=rs.user_id WHERE rs.tenant_id=p_tenant_id AND rs.calculated_date=p_reference_date),
  calc AS (SELECT b.*,CASE WHEN b.override_status IS NOT NULL THEN b.override_status WHEN NOT COALESCE(b.onboarding_completed,false) THEN 'onboarding' WHEN b.consultation_overdue THEN 'return_overdue' WHEN b.plan_expires_at IS NOT NULL AND (b.plan_expires_at AT TIME ZONE 'America/Sao_Paulo')::date < p_reference_date-v_plan_grace THEN 'plan_expired' WHEN b.plan_expiring THEN 'plan_expiring' WHEN b.next_appointment_at IS NOT NULL THEN 'awaiting_consultation' WHEN b.completion_date IS NOT NULL AND b.completion_date BETWEEN p_reference_date-v_protocol_window AND p_reference_date THEN 'protocol_completed' WHEN b.last_appointment_at IS NOT NULL AND (p_reference_date-(b.last_appointment_at AT TIME ZONE 'America/Sao_Paulo')::date)>=v_return_days THEN 'return_overdue' WHEN COALESCE(b.days_since_activity,0)>=v_reactivation_days THEN 'reactivation' ELSE 'active_followup' END status_calc FROM base b)
  UPDATE public.patient_risk_scores rs SET lifecycle_status=c.status_calc,lifecycle_next_action=COALESCE(c.override_next_action,CASE c.status_calc WHEN 'onboarding' THEN 'Concluir ativação e orientar os primeiros passos.' WHEN 'awaiting_consultation' THEN 'Aguardar a consulta e revisar preparo/pré-consulta.' WHEN 'return_overdue' THEN 'Revisar necessidade de retorno e definir contato.' WHEN 'plan_expiring' THEN 'Revisar continuidade e renovação antes do vencimento.' WHEN 'plan_expired' THEN 'Definir renovação, encerramento ou reativação.' WHEN 'protocol_completed' THEN 'Revisar resultado, conclusão e próximo protocolo/fase.' WHEN 'reactivation' THEN 'Avaliar motivo clínico para reativação e próximo passo.' WHEN 'care_completed' THEN 'Acompanhamento encerrado; manter histórico e critérios de reentrada.' ELSE 'Manter acompanhamento conforme o método atual.' END),lifecycle_details=jsonb_build_object('source',CASE WHEN c.override_status IS NOT NULL THEN 'manual_override' ELSE 'engine' END,'override_note',c.override_note,'plan_expires_at',c.plan_expires_at,'protocol_status',c.protocol_status,'protocol_end_date',c.protocol_end_date,'protocol_completion_date',c.completion_date,'next_appointment_at',c.next_appointment_at,'last_appointment_at',c.last_appointment_at) FROM calc c WHERE rs.id=c.id;
  GET DIAGNOSTICS v_rows=ROW_COUNT;RETURN v_rows;
END;$function$;

CREATE OR REPLACE FUNCTION public.refresh_phase_advancement_eligibility(p_tenant_id uuid,p_reference_date date DEFAULT ((now() AT TIME ZONE 'America/Sao_Paulo'))::date)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path='public' AS $function$
DECLARE v_rows int:=0;
BEGIN
  UPDATE public.patient_risk_scores SET phase_review_eligible=false,current_method_phase_id=NULL,phase_review_details='{}'::jsonb,signals=COALESCE(signals,'{}'::jsonb)-'phase_review_eligible'-'current_method_phase_id'-'next_phase_id',reasons=COALESCE((SELECT jsonb_agg(elem) FROM jsonb_array_elements(COALESCE(reasons,'[]'::jsonb)) elem WHERE elem->>'code'<>'phase_review_eligible'),'[]'::jsonb) WHERE tenant_id=p_tenant_id AND calculated_date=p_reference_date;
  WITH current_phase AS (
    SELECT DISTINCT ON(fp.paciente_id) fp.paciente_id user_id,fp.method_phase_id,fp.inicio,mp.method_id,mp.name phase_name,mp.sort_order,mp.advancement_criteria,next_mp.id next_phase_id,next_mp.name next_phase_name
    FROM public.fase_paciente fp JOIN public.method_phases mp ON mp.id=fp.method_phase_id LEFT JOIN LATERAL(SELECT nmp.id,nmp.name FROM public.method_phases nmp WHERE nmp.method_id=mp.method_id AND nmp.tenant_id=mp.tenant_id AND nmp.sort_order>mp.sort_order ORDER BY nmp.sort_order LIMIT 1) next_mp ON true JOIN public.profiles p ON p.user_id=fp.paciente_id AND p.tenant_id=p_tenant_id
    WHERE fp.fim IS NULL AND mp.tenant_id=p_tenant_id AND p.role='patient' ORDER BY fp.paciente_id,fp.inicio DESC,fp.created_at DESC
  ), weekly_state AS (SELECT cp.user_id,max((wr.created_at AT TIME ZONE 'America/Sao_Paulo')::date) last_weekly_date FROM current_phase cp LEFT JOIN public.weekly_checkin_responses wr ON wr.user_id=cp.user_id AND (wr.created_at AT TIME ZONE 'America/Sao_Paulo')::date>=cp.inicio GROUP BY cp.user_id),
  latest_protocol AS (SELECT DISTINCT ON(cp.user_id) cp.user_id,pa.status,pa.progress_percentage,pa.created_at FROM current_phase cp LEFT JOIN public.protocol_assignments pa ON pa.user_id=cp.user_id AND COALESCE(pa.start_date,(pa.created_at AT TIME ZONE 'America/Sao_Paulo')::date)>=cp.inicio ORDER BY cp.user_id,pa.created_at DESC NULLS LAST),
  evaluation AS (SELECT prs.id risk_score_id,prs.user_id,cp.method_phase_id,cp.phase_name,cp.next_phase_id,cp.next_phase_name,cp.inicio,cp.advancement_criteria,prs.adherence_7d,ws.last_weekly_date,(ws.last_weekly_date IS NOT NULL AND ws.last_weekly_date>=GREATEST(cp.inicio,p_reference_date-7)) weekly_recent,(lp.created_at IS NOT NULL AND (lower(COALESCE(lp.status,'')) IN('completed','concluido','concluído','finished') OR COALESCE(lp.progress_percentage,0)>=100)) protocol_completed,GREATEST(0,p_reference_date-cp.inicio) days_in_phase,COALESCE((cp.advancement_criteria->>'enabled')::boolean,false) criteria_enabled,COALESCE(NULLIF(cp.advancement_criteria->>'mode',''),'all') criteria_mode,(cp.advancement_criteria->>'min_days_in_phase')::int min_days,(cp.advancement_criteria->>'min_adherence_7d')::numeric min_adherence,COALESCE((cp.advancement_criteria->>'require_weekly_checkin')::boolean,false) require_weekly,COALESCE((cp.advancement_criteria->>'require_protocol_completion')::boolean,false) require_protocol,COALESCE((cp.advancement_criteria->>'require_manual_approval')::boolean,true) require_manual_approval,COALESCE(cp.advancement_criteria->>'custom_note','') custom_note FROM public.patient_risk_scores prs JOIN current_phase cp ON cp.user_id=prs.user_id LEFT JOIN weekly_state ws ON ws.user_id=prs.user_id LEFT JOIN latest_protocol lp ON lp.user_id=prs.user_id WHERE prs.tenant_id=p_tenant_id AND prs.calculated_date=p_reference_date),
  counted AS (SELECT e.*,((e.min_days IS NOT NULL)::int+(e.min_adherence IS NOT NULL)::int+e.require_weekly::int+e.require_protocol::int) configured_count,((CASE WHEN e.min_days IS NOT NULL AND e.days_in_phase>=e.min_days THEN 1 ELSE 0 END)+(CASE WHEN e.min_adherence IS NOT NULL AND COALESCE(e.adherence_7d,0)>=e.min_adherence THEN 1 ELSE 0 END)+(CASE WHEN e.require_weekly AND e.weekly_recent THEN 1 ELSE 0 END)+(CASE WHEN e.require_protocol AND e.protocol_completed THEN 1 ELSE 0 END)) passed_count FROM evaluation e),
  final_eval AS (SELECT c.*,(c.criteria_enabled AND c.next_phase_id IS NOT NULL AND c.configured_count>0 AND CASE WHEN c.criteria_mode='any' THEN c.passed_count>=1 ELSE c.passed_count=c.configured_count END) eligible FROM counted c)
  UPDATE public.patient_risk_scores prs SET current_method_phase_id=f.method_phase_id,phase_review_eligible=f.eligible,phase_review_details=jsonb_build_object('phase_name',f.phase_name,'next_phase_id',f.next_phase_id,'next_phase_name',f.next_phase_name,'phase_started_at',f.inicio,'criteria_enabled',f.criteria_enabled,'mode',f.criteria_mode,'configured_count',f.configured_count,'passed_count',f.passed_count,'require_manual_approval',f.require_manual_approval,'custom_note',f.custom_note,'checks',jsonb_build_object('days_in_phase',jsonb_build_object('configured',f.min_days IS NOT NULL,'current',f.days_in_phase,'required',f.min_days,'passed',CASE WHEN f.min_days IS NULL THEN NULL ELSE f.days_in_phase>=f.min_days END),'adherence_7d',jsonb_build_object('configured',f.min_adherence IS NOT NULL,'current',f.adherence_7d,'required',f.min_adherence,'passed',CASE WHEN f.min_adherence IS NULL THEN NULL ELSE COALESCE(f.adherence_7d,0)>=f.min_adherence END),'weekly_checkin',jsonb_build_object('configured',f.require_weekly,'last_date',f.last_weekly_date,'passed',CASE WHEN NOT f.require_weekly THEN NULL ELSE f.weekly_recent END),'protocol_completion',jsonb_build_object('configured',f.require_protocol,'passed',CASE WHEN NOT f.require_protocol THEN NULL ELSE f.protocol_completed END))),signals=COALESCE(prs.signals,'{}'::jsonb)||jsonb_build_object('phase_review_eligible',f.eligible,'current_method_phase_id',f.method_phase_id,'next_phase_id',f.next_phase_id),reasons=COALESCE(prs.reasons,'[]'::jsonb)||CASE WHEN f.eligible THEN jsonb_build_array(jsonb_build_object('code','phase_review_eligible','phase_name',f.phase_name,'next_phase_name',f.next_phase_name,'manual_approval_required',f.require_manual_approval)) ELSE '[]'::jsonb END FROM final_eval f WHERE prs.id=f.risk_score_id;
  GET DIAGNOSTICS v_rows=ROW_COUNT;RETURN v_rows;
END;$function$;

REVOKE ALL ON FUNCTION public.refresh_patient_operational_snapshot(uuid,date) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.refresh_patient_lifecycle_states(uuid,date) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.refresh_phase_advancement_eligibility(uuid,date) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_patient_operational_snapshot(uuid,date) TO service_role;
GRANT EXECUTE ON FUNCTION public.refresh_patient_lifecycle_states(uuid,date) TO service_role;
GRANT EXECUTE ON FUNCTION public.refresh_phase_advancement_eligibility(uuid,date) TO service_role;
