create or replace function public.apply_crm_contact_outcome() returns trigger language plpgsql set search_path=public as $$
declare v_type public.crm_outcome_types%rowtype;v_next timestamptz;
begin
 select*into v_type from public.crm_outcome_types where id=new.outcome_type_id and tenant_id=new.tenant_id;if v_type.id is null then raise exception 'Resultado inválido para esta clínica';end if;
 if not exists(select 1 from public.crm_contacts c where c.id=new.contact_id and c.tenant_id=new.tenant_id)then raise exception 'Contato inválido para esta clínica';end if;
 if v_type.next_stage_id is not null and not exists(select 1 from public.crm_stages s where s.id=v_type.next_stage_id and s.tenant_id=new.tenant_id)then raise exception 'Etapa de destino inválida';end if;
 if v_type.terminal then v_next:=null;elsif v_type.followup_days is not null then v_next:=new.occurred_at+make_interval(days=>greatest(v_type.followup_days,0));else select next_action_at into v_next from public.crm_contacts where id=new.contact_id;end if;
 update public.crm_contacts set last_contact_at=new.occurred_at,next_action_at=v_next,do_not_contact=case when v_type.set_do_not_contact then true else do_not_contact end,stage_id=coalesce(v_type.next_stage_id,stage_id),stage_sync_mode=case when v_type.next_stage_id is not null then'manual'else stage_sync_mode end,updated_at=now() where id=new.contact_id and tenant_id=new.tenant_id;
 insert into public.crm_contact_events(tenant_id,contact_id,event_type,title,note,to_value,metadata,source,actor_user_id,created_at) values(new.tenant_id,new.contact_id,'contact_outcome','Resultado da abordagem: '||v_type.name,new.note,jsonb_build_object('outcome_type_id',v_type.id,'code',v_type.code,'name',v_type.name),jsonb_build_object('counts_as_conversion',v_type.counts_as_conversion,'counts_as_recovery',v_type.counts_as_recovery),'staff',new.actor_user_id,new.occurred_at);return new;
end$$;
revoke all on function public.apply_crm_contact_outcome() from public,anon,authenticated;

create or replace function public.sync_app_patients_to_crm(p_tenant_id uuid,p_reference_date date default(now()at time zone'America/Sao_Paulo')::date) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_inserted integer:=0;v_updated integer:=0;v_linked integer:=0;v_country text:='55';
begin
 if p_tenant_id is null then raise exception 'tenant_id é obrigatório';end if;select coalesce(nullif(default_country_code,''),'55')into v_country from public.crm_import_settings where tenant_id=p_tenant_id;v_country:=coalesce(v_country,'55');perform public.ensure_default_crm_stage_mapping_rules(p_tenant_id);
 with latest_risk as(select distinct on(rs.user_id)rs.user_id,rs.lifecycle_status,rs.operational_status,rs.last_activity_date from public.patient_risk_scores rs where rs.tenant_id=p_tenant_id and rs.calculated_date<=p_reference_date order by rs.user_id,rs.calculated_date desc),src0 as(select p.user_id,p.name,p.email,p.phone,p.birth_date,p.primary_goal,lr.lifecycle_status,lr.operational_status,lr.last_activity_date,lower(nullif(trim(p.email),''))email_norm,regexp_replace(coalesce(p.phone,''),'\D','','g')phone_digits,public.resolve_crm_stage_id(p_tenant_id,lr.lifecycle_status,lr.operational_status)stage_id from public.profiles p left join latest_risk lr on lr.user_id=p.user_id where p.tenant_id=p_tenant_id and lower(coalesce(p.role,''))='patient'),source_rows as(select s.*,case when length(s.phone_digits)in(10,11)then v_country||s.phone_digits else nullif(s.phone_digits,'')end phone_norm from src0 s),candidates as(select s.user_id,c.id,count(*)over(partition by s.user_id)matches from source_rows s join public.crm_contacts c on c.tenant_id=p_tenant_id and c.linked_user_id is null and((s.email_norm is not null and c.email_normalized=s.email_norm)or(s.phone_norm is not null and c.phone_normalized=s.phone_norm))),linked as(update public.crm_contacts c set linked_user_id=x.user_id,last_import_id=null,metadata=coalesce(c.metadata,'{}'::jsonb)||jsonb_build_object('linked_from','app'),updated_at=now() from candidates x where x.matches=1 and c.id=x.id returning c.id)select count(*)into v_linked from linked;
 with latest_risk as(select distinct on(rs.user_id)rs.user_id,rs.lifecycle_status,rs.operational_status,rs.last_activity_date from public.patient_risk_scores rs where rs.tenant_id=p_tenant_id and rs.calculated_date<=p_reference_date order by rs.user_id,rs.calculated_date desc),src0 as(select p.user_id,p.name,p.email,p.phone,p.birth_date,p.primary_goal,lr.lifecycle_status,lr.operational_status,lr.last_activity_date,lower(nullif(trim(p.email),''))email_norm,regexp_replace(coalesce(p.phone,''),'\D','','g')phone_digits,public.resolve_crm_stage_id(p_tenant_id,lr.lifecycle_status,lr.operational_status)stage_id from public.profiles p left join latest_risk lr on lr.user_id=p.user_id where p.tenant_id=p_tenant_id and lower(coalesce(p.role,''))='patient'),source_rows as(select s.*,case when length(s.phone_digits)in(10,11)then v_country||s.phone_digits else nullif(s.phone_digits,'')end phone_norm from src0 s),ins as(insert into public.crm_contacts(tenant_id,linked_user_id,stage_id,stage_sync_mode,source,name,email,phone,whatsapp,birth_date,primary_goal,last_activity_at,email_normalized,phone_normalized,metadata)select p_tenant_id,s.user_id,s.stage_id,'automatic','app',coalesce(nullif(s.name,''),coalesce(s.email,'Paciente')),s.email,s.phone,s.phone,s.birth_date,s.primary_goal,case when s.last_activity_date is not null then(s.last_activity_date::timestamp at time zone'America/Sao_Paulo')else null end,s.email_norm,s.phone_norm,jsonb_build_object('synced_from','profiles','lifecycle_status',s.lifecycle_status,'operational_status',s.operational_status)from source_rows s where s.stage_id is not null and not exists(select 1 from public.crm_contacts c where c.tenant_id=p_tenant_id and c.linked_user_id=s.user_id)returning id)select count(*)into v_inserted from ins;
 with latest_risk as(select distinct on(rs.user_id)rs.user_id,rs.lifecycle_status,rs.operational_status,rs.last_activity_date from public.patient_risk_scores rs where rs.tenant_id=p_tenant_id and rs.calculated_date<=p_reference_date order by rs.user_id,rs.calculated_date desc),src0 as(select p.user_id,p.name,p.email,p.phone,p.birth_date,p.primary_goal,lr.lifecycle_status,lr.operational_status,lr.last_activity_date,lower(nullif(trim(p.email),''))email_norm,regexp_replace(coalesce(p.phone,''),'\D','','g')phone_digits,public.resolve_crm_stage_id(p_tenant_id,lr.lifecycle_status,lr.operational_status)stage_id from public.profiles p left join latest_risk lr on lr.user_id=p.user_id where p.tenant_id=p_tenant_id and lower(coalesce(p.role,''))='patient'),source_rows as(select s.*,case when length(s.phone_digits)in(10,11)then v_country||s.phone_digits else nullif(s.phone_digits,'')end phone_norm from src0 s),upd as(update public.crm_contacts c set name=coalesce(nullif(s.name,''),c.name),email=coalesce(s.email,c.email),phone=coalesce(s.phone,c.phone),whatsapp=coalesce(s.phone,c.whatsapp),birth_date=coalesce(s.birth_date,c.birth_date),primary_goal=coalesce(s.primary_goal,c.primary_goal),email_normalized=coalesce(s.email_norm,c.email_normalized),phone_normalized=coalesce(s.phone_norm,c.phone_normalized),stage_id=case when c.stage_sync_mode='automatic' and not c.do_not_contact and s.stage_id is not null then s.stage_id else c.stage_id end,last_activity_at=case when s.last_activity_date is not null then(s.last_activity_date::timestamp at time zone'America/Sao_Paulo')else c.last_activity_at end,last_import_id=null,metadata=coalesce(c.metadata,'{}'::jsonb)||jsonb_build_object('synced_from','profiles','lifecycle_status',s.lifecycle_status,'operational_status',s.operational_status),updated_at=now() from source_rows s where c.tenant_id=p_tenant_id and c.linked_user_id=s.user_id returning c.id)select count(*)into v_updated from upd;
 return jsonb_build_object('inserted',v_inserted,'linked',v_linked,'updated',v_updated,'reference_date',p_reference_date);
end$$;
revoke all on function public.sync_app_patients_to_crm(uuid,date) from public,anon,authenticated;
grant execute on function public.sync_app_patients_to_crm(uuid,date) to service_role;
